name: Run Unit Test via Pytest and build Image
  
on: [push]  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        python-version: ["3.12"]
    steps:  
    - uses: actions/checkout@v3  
    - name: Set up Python ${{ matrix.python-version }}  
      uses: actions/setup-python@v4  
      with:  
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      run: |  
          python -m pip install --upgrade pip  
          pip install poetry
    - name: Install dependencies
      run: |  
          poetry install 
    - name: Update path to enable importing
      run: echo "PYTHONPATH=home/runner/work/ToxicML" >> $GITHUB_ENV
      shell: bash
    - name: Run tests
      run: |  
          poetry run pytest .
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: custibor29/toxicml:latest
